"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mathRandom = exports.mathPow = exports.divi = exports.multi = exports.sum = exports.add = exports.JWarning = exports.JUnhandledRejection = exports.JuncaughtExceptionMonitor = exports.JUnCaughtException = exports.JRejectionHandled = exports.JmultipleResolves = exports.JExit = exports.JColorRandom = exports.JColor = void 0;
const jfacile_1 = require("./jfacile");
Object.defineProperty(exports, "JColor", { enumerable: true, get: function () { return jfacile_1.JColor; } });
Object.defineProperty(exports, "JColorRandom", { enumerable: true, get: function () { return jfacile_1.JColorRandom; } });
const process_1 = require("./process");
Object.defineProperty(exports, "JExit", { enumerable: true, get: function () { return process_1.JExit; } });
Object.defineProperty(exports, "JmultipleResolves", { enumerable: true, get: function () { return process_1.JmultipleResolves; } });
Object.defineProperty(exports, "JRejectionHandled", { enumerable: true, get: function () { return process_1.JRejectionHandled; } });
Object.defineProperty(exports, "JUnCaughtException", { enumerable: true, get: function () { return process_1.JUnCaughtException; } });
Object.defineProperty(exports, "JuncaughtExceptionMonitor", { enumerable: true, get: function () { return process_1.JuncaughtExceptionMonitor; } });
Object.defineProperty(exports, "JUnhandledRejection", { enumerable: true, get: function () { return process_1.JUnhandledRejection; } });
Object.defineProperty(exports, "JWarning", { enumerable: true, get: function () { return process_1.JWarning; } });
const math_1 = require("./math");
Object.defineProperty(exports, "add", { enumerable: true, get: function () { return math_1.add; } });
Object.defineProperty(exports, "sum", { enumerable: true, get: function () { return math_1.sum; } });
Object.defineProperty(exports, "multi", { enumerable: true, get: function () { return math_1.multi; } });
Object.defineProperty(exports, "divi", { enumerable: true, get: function () { return math_1.divi; } });
Object.defineProperty(exports, "mathPow", { enumerable: true, get: function () { return math_1.mathPow; } });
Object.defineProperty(exports, "mathRandom", { enumerable: true, get: function () { return math_1.mathRandom; } });
