"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mathRandom = exports.mathPow = exports.divi = exports.multi = exports.sum = exports.difference = exports.JWarning = exports.JUnhandledRejection = exports.JuncaughtExceptionMonitor = exports.JUnCaughtException = exports.JRejectionHandled = exports.JmultipleResolves = exports.JExit = exports.route = exports.run = exports.JColorRandom = exports.JColor = void 0;
const color_1 = require("./color-engine/color");
Object.defineProperty(exports, "JColor", { enumerable: true, get: function () { return color_1.JColor; } });
Object.defineProperty(exports, "JColorRandom", { enumerable: true, get: function () { return color_1.JColorRandom; } });
const express_1 = require("./express-engine/express");
Object.defineProperty(exports, "run", { enumerable: true, get: function () { return express_1.run; } });
Object.defineProperty(exports, "route", { enumerable: true, get: function () { return express_1.route; } });
// import { Client } from "./client-engine/client";
const process_1 = require("./process-engine/process");
Object.defineProperty(exports, "JExit", { enumerable: true, get: function () { return process_1.JExit; } });
Object.defineProperty(exports, "JmultipleResolves", { enumerable: true, get: function () { return process_1.JmultipleResolves; } });
Object.defineProperty(exports, "JRejectionHandled", { enumerable: true, get: function () { return process_1.JRejectionHandled; } });
Object.defineProperty(exports, "JUnCaughtException", { enumerable: true, get: function () { return process_1.JUnCaughtException; } });
Object.defineProperty(exports, "JuncaughtExceptionMonitor", { enumerable: true, get: function () { return process_1.JuncaughtExceptionMonitor; } });
Object.defineProperty(exports, "JUnhandledRejection", { enumerable: true, get: function () { return process_1.JUnhandledRejection; } });
Object.defineProperty(exports, "JWarning", { enumerable: true, get: function () { return process_1.JWarning; } });
const maths_1 = require("./maths-engine/maths");
Object.defineProperty(exports, "difference", { enumerable: true, get: function () { return maths_1.difference; } });
Object.defineProperty(exports, "sum", { enumerable: true, get: function () { return maths_1.sum; } });
Object.defineProperty(exports, "multi", { enumerable: true, get: function () { return maths_1.multi; } });
Object.defineProperty(exports, "divi", { enumerable: true, get: function () { return maths_1.divi; } });
Object.defineProperty(exports, "mathPow", { enumerable: true, get: function () { return maths_1.mathPow; } });
Object.defineProperty(exports, "mathRandom", { enumerable: true, get: function () { return maths_1.mathRandom; } });
